[WIP] dummy auth model
RocketChat/RC4Community pull request #171
Opened 2022-06-17 17:25 UTC by sidmohanty11

This PR introduces,
- [ ] a dummy authentication model
- [ ] removes firebase error
- [ ] fixes all the console errors for a smooth development experience

2022-06-17 17:27 UTC, sidmohanty11 commented
## Dummy User Authentication Model

https://user-images.githubusercontent.com/73601258/174348400-90d4baa5-4026-4e1f-9fe5-8851cddff741.mp4

2022-07-03 13:08 UTC, sidmohanty11 commented
I've fixed almost all errors that were arising:
- firebase error
- `slideCount` error

There remains only one error (`<button> inside <button>`) which is coming from the Menubar component because we are using Navbar.Toggle but inside for styling, we are using another button. This should be fixed with the new Menubar component which is being worked on in this [PR](https://github.com/RocketChat/RC4Community/pull/155).

![image](https://user-images.githubusercontent.com/73601258/177041034-942e8cf1-b5d5-44a2-ab6a-634bbc8f7f74.png)

2022-07-03 18:58 UTC, debdutdeb requested changes

2022-07-03 18:58 UTC, debdutdeb commented on app/lib/auth/RocketChatOAuthProvider.js
> +    token: urlJoin(process.env.NEXTAUTH_URL ?? "http://localhost:3000",'/api/auth/rocketchat-token-legacy'),
```suggestion
    token: urlJoin(process.env.NEXTAUTH_URL || "http://localhost:3000",'/api/auth/rocketchat-token-legacy'),
```

2022-07-03 18:58 UTC, debdutdeb commented on app/pages/api/auth/[...nextauth].js
> +				rocketChatUrl: process.env.ROCKETCHAT_URL ?? "http://localhost:3000"
Make sure empty strings aren't an issue here.

2022-07-03 18:58 UTC, debdutdeb commented on app/components/auth/dummy/ui/DummyLoginButton.js
> +  const [isOpen, setOpen] = useState(false);
Use more explicit names. What is `open`ness supposed to represent here? suggestion: `isLoginUiOpen` never be afraid of over-explained variable names, most of us love them.

2022-07-03 18:58 UTC, debdutdeb commented on app/components/auth/dummy/lib/function.js
> +  let user = JSON.parse(sessionStorage.getItem("dummy_user"));
No need for this, you're already checking session storage on `DummyLoginButton`.

2022-07-03 18:58 UTC, debdutdeb commented on app/components/auth/dummy/ui/DummyLoginUI.js
> +  }
Move them to `DummyLoginButton` and just pass the `user` state. Pass these as `handleLogin` and `handleLogout`.

2022-07-03 18:58 UTC, debdutdeb commented on app/components/auth/dummy/ui/DummyLoginUI.js
> +      !user.id ? <div className="d-flex flex-column align-items-center my-3">
Shift the login please, `user.id ? ... : ...`

2022-07-03 18:58 UTC, debdutdeb commented on app/components/menubar.js
> +          {Cookies.get("user") ? (
Save the cookie value in some variable pls.

2022-07-03 18:58 UTC, debdutdeb commented on app/components/menubar.js
> +                  <Link href={`/profile/${Cookies.get("user")}`}>
Variable for the cookie.

2022-07-05 16:01 UTC, Sing-Li requested changes
![image](https://user-images.githubusercontent.com/122633/177369491-69a22357-543b-4a5b-8ad3-4466fe6481ed.png)


Works well @sidmohanty11      But what happened to the menu/TopNav?    It would be good to have the menu change depending on the logged in state as well.

2022-07-06 07:35 UTC, sidmohanty11 commented
It is there in my case.
![image](https://user-images.githubusercontent.com/73601258/177495268-d237980a-c579-494d-a16a-4963a3908f7c.png)

Is it due to cms uninitialized? But that should break the app, right? Can you check with running cms?

2022-07-07 16:50 UTC, debdutdeb commented on app/components/auth/dummy/ui/DummyLoginButton.js
> +  },[])
Move all `createDummyUser` or validation functions in the same file.

2022-07-09 07:22 UTC, sidmohanty11 commented on app/components/auth/dummy/ui/DummyLoginButton.js
> +  },[])
Great idea! Ah, I just went with the conventional code structure of other auths. I will make the changes!

2022-07-09 07:40 UTC, sidmohanty11 commented
Did a clean clone and install, the top nav works for me. 
![image](https://user-images.githubusercontent.com/73601258/178096621-7f891c21-e2a2-43c0-92f1-278c8602acb1.png)

2022-07-14 16:24 UTC, merged