Fixes carousel bug
RocketChat/RC4Community pull request #199
Opened 2022-11-12 13:03 UTC by vasucp1207

- Issue no https://github.com/RocketChat/RC4Community/issues/198

https://user-images.githubusercontent.com/85363195/201475252-0699b0cb-cfbc-4354-9f06-1e527c611b10.mov

2022-11-12 13:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/RC4Community?pullRequest=199) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/RC4Community?pullRequest=199) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/RC4Community?pullRequest=199) it.</sub>

2022-11-12 15:30 UTC, Palanikannan1437 requested changes
Hey @vasucp1207, it's not a good idea to commit package-lock.json, it'll cause problems for others most of the time. Please make the necessary changes to your PR

Thank you

2022-11-12 15:58 UTC, Palanikannan1437 commented
Hey @vasucp1207, sorry for not being very clear...you didn't have to delete the package-lock.json file, you just have to remove it from your PR.

One approach could be...you could revert your old commit's changes and then force push the changes again in which your `package-lock.json` isn't there in your git diff. 

Thank you 😄

2022-11-12 16:07 UTC, vasucp1207 commented
@Palanikannan1437, I do not change anything in package.json, I don't know how it changes automatically.
I commit the changes again but it appears again can you help me?

2022-11-12 16:40 UTC, Palanikannan1437 commented
> @Palanikannan1437, I do not change anything in package.json, I don't know how it changes automatically.
> I commit the changes but it appears again can you help me?

Hey yeah sure, so when you install a package using the `npm install ....` command or if it's internally run due to our existing scripts, the package.lock.json is generated

So basically while staging your files, instead of `git add .` you'd have to manually stage the files you changed and want to push.😄

2022-11-12 16:41 UTC, vasucp1207 commented
@Palanikannan1437 I remove the package-lock.json is it okay now please tell me.

2022-11-12 16:48 UTC, Palanikannan1437 commented
> @Palanikannan1437 I remove the package-lock.json is it okay now please tell me.

Sorry, but still it's in the git diff

<img width="765" alt="image" src="https://user-images.githubusercontent.com/73993394/201484946-a730f7d2-3e62-45f2-8ae9-09d5311701df.png">

> Hey @vasucp1207, sorry for not being very clear...you didn't have to delete the package-lock.json file, you just have to remove it from your PR.
> 
> One approach could be...you could revert your old commit's changes and then force push the changes again in which your `package-lock.json` isn't there in your git diff.
> 
> Thank you 😄

Please try to research and follow up on this approach of `soft resetting` and `force pushing` in git and let us know if you face any issues. Thank you!

2022-11-12 17:25 UTC, vasucp1207 commented
@Palanikannan1437 I think it's done now.

2022-11-13 12:43 UTC, Palanikannan1437 commented
Hey @vasucp1207, that was a great catch and thank you for your valuable contribution!

But currently there's no need to change the existing custom button ui/button component on our slider...instead it'd be better if you could debug and add the missing `onClick` method on our custom `PrevArrow` and `NextArrow` by going through [react-slick's custom arrow documentation](https://react-slick.neostack.com/docs/example/custom-arrows/).

Thank you and hope to see your PR get merged soon 😄

2022-11-13 12:46 UTC, Palanikannan1437 commented
> @Palanikannan1437 I think it's done now.

That was awesome and kudos on being able to remove the `package-lock.json` from your PR!! 

Hope you got to learn something out of it!!

2022-11-13 12:58 UTC, vasucp1207 commented
@Palanikannan1437, but what is the need to add the custom arrows when react-slick provides the arrows by default?

2022-11-13 13:11 UTC, Palanikannan1437 commented
> provides

Hey, I'm not sure but it was a design choice made by our contributors...and since there's just a small function they missed, there's no need to remove the entire component but instead you could add the missing function.

@Dnouv and @irffanasiff could better guide here, thank you!

2022-11-15 15:20 UTC, Sing-Li commented
@vasucp1207   Yes.  As @Palanikannan1437   the custom arrows are BY DESIGN.   We had a designer contributor making sure that the UI elements are consistent, color schemes are attractive etc.     This is typical of all production project.    You can't use the default "just because it is there".        Please update your PR asap.

2022-11-16 07:18 UTC, vasucp1207 commented
@Sing-Li, OK

2022-11-16 11:55 UTC, Palanikannan1437 commented on app/components/newscarousel.js
>  const NextArrow = ({ currentSlide, slideCount, ...props }) => {
You could simply de-structure the onClick method here itself! Thank you!

2022-11-16 11:58 UTC, Palanikannan1437 commented on app/components/newscarousel.js
>  const PrevArrow = ({ currentSlide, slideCount, ...props }) => {
Likewise, you could de-structure the onClick method here itself! Thank you!

2022-11-17 07:21 UTC, Palanikannan1437 commented
LGTM @vasucp1207 !! 🥳

@Sing-Li I've reviewed the changes, please consider merging them, thank you!

2022-11-17 07:21 UTC, Palanikannan1437 commented
LGTM @vasucp1207 !! 🥳

@Sing-Li I've reviewed the changes, please consider merging them, thank you!

2022-11-17 10:40 UTC, Sing-Li commented
Congrats @vasucp1207

2022-11-17 10:41 UTC, merged