[WIP] RocketChatLinkButton Component
RocketChat/RC4Community pull request #47
Opened 2022-01-23 16:13 UTC by sidmohanty11

Created a new RocketChatLinkButton Component which by default redirects to https://open.rocket.chat
https://user-images.githubusercontent.com/73601258/150687434-46c98142-5c44-4586-96eb-11d6c9870cf0.mp4

2022-01-23 16:27 UTC, Sing-Li requested changes

2022-01-23 16:27 UTC, Sing-Li commented on app/components/menubar.js
> +import { useState } from "react";
Menubar is NOT your component. Keep your own component completely independent.

2022-01-23 16:27 UTC, Sing-Li commented on app/styles/Menubar.module.css
> +  content: ".";
Menubar is *not* your component.   Keep your component independent.

Any coupling should be done via the bootstrap "design language"

2022-01-23 16:27 UTC, Sing-Li commented
Please revise this PR.   Do not keep closing and openning new PRs.  Thanks.

2022-01-25 13:00 UTC, sidmohanty11 commented
@Sing-Li I've added the rocketchatlinkbutton component and kept it independent, please let me know if we need to make some other changes. 

Thank you

2022-01-25 17:40 UTC, Sing-Li commented
@sidmohanty11    Please resolve the trivial conflict and  it will be good-to-merge.  Thx

2022-01-25 18:58 UTC, sidmohanty11 commented
Done! @Sing-Li

2022-01-25 20:20 UTC, merged