[NEW] Add form components "creator kit"
RocketChat/RC4Community pull request #84
Opened 2022-02-28 16:13 UTC by Dnouv

This PR introduces a form component.
Here are some preview images.
<img height="300" width="400" src="https://user-images.githubusercontent.com/61188295/156017575-d5aa08b8-a157-4e39-a439-8f8d2ee98bdc.png" />
<img height="300" width="400" src="https://user-images.githubusercontent.com/61188295/156017609-abf8ef41-7259-4679-9f0a-d5559e1a140e.png" />
<img height="300" width="400" src="https://user-images.githubusercontent.com/61188295/156017401-0ba4a515-cd71-4c56-93c0-1167fc966848.png" />

Thank you!

Note: Please do not merge. WIP

2022-02-28 19:19 UTC, Sing-Li commented
Thanks @Dnouv !    Cool.    

The current workflow fo RC4Community has no interactive "design time" behaviours.   Since your code here entails only interactive design-time behaviours, it is best to have it running standalone as a separate tool.

It can generate the actual JSX , or the source code of the react component to display/manage the form directly.   

Or a better solution is if this tool will write the "form description data" to strapi, and then have a set of custom ReactJS tag that can render this form during build time by fetching the "form description data".

2022-03-03 13:27 UTC, Sing-Li requested changes
As per our conversation on Rocket.Chat @Dnouv 

1) please place your creation tool as an INDEPENDENT TOOL under `/contrib/formcreator` directory, it should be a standalone 100% independent nodeJS based tool - and not part of RC4Community framework

2) please create components under `components` directory that will be re-usable and renders the form for the community builder

3) please create a demo page under `pages/formdemo` that shows FOUR or FIVE instances of your forms components - displaying FOUR or FIVE forms simultaneously on one single page (nothing else) ... this will illustrate to everyone that your component is easily re-usable

Other than the above, please do not add any additional source files that may alter the structure of the project

2022-03-04 13:18 UTC, Sing-Li requested changes

2022-03-04 13:18 UTC, Sing-Li commented on app/pages/forms/formdemo.js
> +      <RCform formFields={formFields} />
Need to craft `RCform` as a re-usable component.   

Show us on this demo page.   Add 4 or 5  instances of different forms.

Similar to:
```
<h1>Sample of Form Component in Action</h1>
<Row>
<Col>
  <RCform  id="customersatisfaction" />
  </Col>
  <Col>
   <RCform id="survey1"/>
   </Col>
 </Row>
 <Row>
<Col>
  <RCform  id="mostlovedmusic" />
  </Col>
  <Col>
   <RCform id="COVID19Questionnaire"/>
   </Col>
 </Row>
 ```

2022-03-12 06:36 UTC, Dnouv commented
A new demo page is added with a few preview forms, here is a screenshot of the page

<img width="500" src="https://user-images.githubusercontent.com/61188295/158007041-a75dc193-e47c-4055-8271-d17d94558476.png" />

Suggestions are most welcomed. Thank you!

2022-03-12 11:13 UTC, Sing-Li requested changes
Incredibly awesome work @Dnouv   🙏 

Please remove package-lock.json from the PR (perhaps add it your .gitignore)  and  it will be good enough for initial merge-down.   

Thanks!

2022-03-12 12:32 UTC, Dnouv commented
Thank you so much for the feedback @Sing-Li .
I've reverted the changes of `package-lock.json` and pushed the changes.
Thank you!

2022-03-12 14:57 UTC, merged