[NEW] GitHub Component Kit
RocketChat/RC4Community pull request #91
Opened 2022-03-13 18:54 UTC by samad-yar-khan

-  [x] I have read the Contributing Guide - https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
  -  [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
  - [x] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  -  [x] I have added necessary documentation (if applicable)
  - [x] Any dependent changes have been merged and published in downstream modules

## Issues

Mentioned in the issue #90 

## Proposed changes (including videos or screenshots)

- Improved database schema for re-usability of component for different repositories. 
- Improved data fetching method in cms (can be re-used when switching from strapi) to provide a better experience for community builders. All data fetching for  the github kit for a repository will be done by a a single `githubKit()` function.
- Replacing individual component tags with a `<Github ... >` tag which can be used to fetch different components of the kit depending on props/parameters.
- Improve github helper functions (which fetch data from the cms into our application) into a single `githubKitData(owner ,name ,[..needs])` function which can fetch relevant data based on the components we wish to use on a particular page.
- Updated [Documentation](https://github.com/samad-yar-khan/RC4Community/tree/githubComponentKit/docs/components/github) . P.S. Refer to the documentation for changes in usability.

2022-03-16 18:10 UTC, samad-yar-khan commented
@Sing-Li I have made some changes and removed the unnecessary code, it would be great if you could review the pull request.

2022-03-18 10:54 UTC, Sing-Li requested changes
Good clean up work, congrats.  

However, you added back package.json  and some index.js modifications

Please remove package.json  and the index.js modifications.   Take a look at other PRs and see how they use a demo page under `pages` to demonstrate their component.  Thanks.

2022-03-18 13:04 UTC, samad-yar-khan commented
@Sing-Li I have made the requested changed : 

- Removed the changes to the `index.js` file. 
- Created a demo page for  the `Github Component Kit` which can be accessed on the route `/github` .
- Removed `.package-lock.json` file .

2022-03-26 15:21 UTC, Sing-Li approved these changes

2022-03-26 15:22 UTC, merged